export TEMP_CUSTOMER_TOKEN="TEMP_CUSTOMER_TOKEN"
export TEMP_ARTIST_TOKEN="TEMP_ARTIST_TOKEN"
export SECRET_KEY="MY_VERY_STRONG_KEY"
export AUTH0_DOMAIN="falbellaihi1.us.auth0.com"
export ALGORITHMS=['RS256']
export FLASK_APP=app.py
export FLASK_ENV=development
export FLASK_DEBUG=True